version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "AbitHelperModelLambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fewqi2ojrss3"
s3_prefix = "AbitHelperModelLambda"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

